### ISSUE TITLE
/img amamiya sora sushi

### ISSUE THREAD

**Issue by hisyotan** [otiai10/chant#177]
https://www.google.co.jp/search?q=amamiya+sora+sushi&espv=2&biw=1382&bih=805&source=lnms&tbm=isch&sa=X&ved=0CAcQ_AUoAmoVChMI_6z2z6SMxwIVyYuUCh1oPQ09

vineのcdnがひっかかってるみたいだけど、Googleができるんだからchantもできるだろ

**Comment by otiai10** [comment]
#148 で治ったのかな？
