### ISSUE TITLE
スタンプのサムネイルを大きくして欲しい

### ISSUE THREAD

**Issue by yayugu** [otiai10/chant#205]
スタンプが小さすぎてどの画像かわかりづらいのでもう少し大きいほうが良い

**Comment by kazuki-akamine** [comment]
マウスオーバーで大きく表示するとかでもよい

**Comment by otiai10** [comment]
それ作ったんだけど、いまいち気に入らなくてrevertした

**Comment by otiai10** [comment]
狗肉の策
https://github.com/otiai10/chant/commit/4d5a675e5105577f77e972bac2e9a87323da2074
