### ISSUE TITLE
mobileはtotsuzenもstamprizeもmuteもいらんわ

### ISSUE THREAD

**Issue by otiai10** [otiai10/chant#210]

**Comment by kazuki-akamine** [comment]
というか Web も酷い

**Comment by kazuki-akamine** [comment]
問題点
・隠しボタン
・文字色が薄い
・文字が小さい
使いづらい UI を目指しましたって感じ

**Comment by otiai10** [comment]
![](http://dash.2-d.jp/wp-content/uploads/2014/01/20140121.jpg)
