### ISSUE TITLE
Use overflow-wrap to nice word wrapping.

### ISSUE THREAD

**Issue by yayugu** [otiai10/chant#243]
Remove

```
div.message-wrapper {
  word-break: break-all;
}
```

Add

https://developer.mozilla.org/en-US/docs/Web/CSS/overflow-wrap

Wrong word-wrap example
![](http://chant.otiai10.com/public/img/uploads/20160629/MjAxNi0wNi0yOSAxODozNDowMS42MzQ0.png)

**Comment by otiai10** [comment]
v2でやる気がする
