### ISSUE TITLE
 Vine の展開機能がほしいです

### ISSUE THREAD

**Issue by otiai10** [otiai10/chant#76]
https://vine.co/v/e7i9TTz7n6M

**Comment by kazz187** [comment]
ほぼりえしょんのための機能ですが、何卒よろしくお願いいたします。

**Comment by otiai10** [comment]
http://www.designwall.com/question/how-do-you-embed-vine-videos/

**Comment by otiai10** [comment]
でしょうな。ユースケースなさすぎわろす
